version: "3"
services:
  networks:
    - vs-codeserver_default:
        external: true

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "192.168.32.3"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "admin"
      DB_MYSQL_PASSWORD: "Lu2504765#"
      DB_MYSQL_NAME: "proxy_db"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./config.json:/app/config/production.json
    depends_on:
      - db
  db:
    container_name: nginx-proxy-manager-db
    image: "jc21/mariadb-aria:10.4.15-innodb"
    environment:
      MYSQL_ROOT_PASSWORD: "Lu557196714657529564#"
      MYSQL_DATABASE: "proxy_db"
      MYSQL_USER: "nginx_user"
      MYSQL_PASSWORD: "Lu2504765#"
    volumes:
      - ./data/mysql:/var/lib/mysql
